%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-event-camera-py
Version:        2.0.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS event_camera_py package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-event-camera-codecs
Requires:       ros-humble-event-camera-msgs
Requires:       ros-humble-pybind11-vendor
Requires:       ros-humble-ros-environment
Requires:       ros-humble-rpyutils
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-ament-cmake
BuildRequires:  ros-humble-ament-cmake-auto
BuildRequires:  ros-humble-ament-cmake-python
BuildRequires:  ros-humble-ament-cmake-ros
BuildRequires:  ros-humble-event-camera-codecs
BuildRequires:  ros-humble-event-camera-msgs
BuildRequires:  ros-humble-pybind11-vendor
BuildRequires:  ros-humble-python-cmake-module
BuildRequires:  ros-humble-ros-environment
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-numpy
BuildRequires:  ros-humble-ament-cmake-clang-format
BuildRequires:  ros-humble-ament-cmake-pytest
BuildRequires:  ros-humble-ament-lint-auto
BuildRequires:  ros-humble-ament-lint-common
BuildRequires:  ros-humble-rclpy
BuildRequires:  ros-humble-rosbag2-py
BuildRequires:  ros-humble-rosbag2-storage-default-plugins
BuildRequires:  ros-humble-rosbag2-storage-mcap
BuildRequires:  ros-humble-rosidl-runtime-py
%endif

%description
Python access for event_camera_msgs.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Thu May 22 2025 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 2.0.1-1
- Autogenerated by Bloom

* Mon Apr 21 2025 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 2.0.0-1
- Autogenerated by Bloom

* Sat Jun 01 2024 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 1.1.6-1
- Autogenerated by Bloom

* Sun Feb 04 2024 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 1.1.4-1
- Autogenerated by Bloom

* Fri Sep 22 2023 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 1.1.3-1
- Autogenerated by Bloom

* Tue Sep 19 2023 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 1.1.2-1
- Autogenerated by Bloom

* Tue Sep 19 2023 Bernd Pfrommer <bernd.pfrommer@gmail.com> - 1.1.1-1
- Autogenerated by Bloom

